name: Java Build and Deploy Pipeline

on:
  push:
     branches:
      - main
  workflow_dispatch:
permissions:
  contents: read
  packages: write

jobs:
  # 1: Build - tests ##
  build:
   uses: java-cicd-pipelines/java-reusable-pipelines/.github/workflows/build-pipeline.yml@main
   secrets:
      SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

  #2: Deploy to GitHub Packages ##
  deploy:
   needs: build
   uses: java-cicd-pipelines/java-reusable-pipelines/.github/workflows/package-deploy.yml@main

  #3: Deploy to Docker ##
  deploy-docker:
   needs: deploy
   uses: java-cicd-pipelines/java-reusable-pipelines/.github/workflows/docker-deploy.yml@main
   
   #4 Deploy to Azure
  deploy-azure:
   needs: deploy-docker
   uses: java-cicd-pipelines/java-reusable-pipelines/.github/workflows/azure-deploy.yml@main
   secrets:
      AZURE_ACR_LOGIN: ${{ secrets.AZURE_ACR_LOGIN }}
      AZURE_ACR_PASS: ${{ secrets.AZURE_ACR_PASS }}
      AZURE_ACR_URL: ${{ secrets.AZURE_ACR_URL }}
      AZURE_APPSERVICE: ${{ secrets.AZURE_APP_SERVICE}}
      