on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  # 1: Build - tests
  build:
    uses: java-cicd-pipelines/java-reusable-pipelines/.github/workflows/reusable-build.yml@main
    with:
     java-version: "17"
     maven-version: "3.8.6"
    secrets:
      SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}