on:
  push:
     branches:
      - main
  workflow_dispatch:

jobs:
  # 1: Build - tests ##
  build:
   uses: java-cicd-pipelines/java-reusable-pipelines/.github/workflows/reusable-build.yml@main
   with:
    java_version: '17'
    maven_version: '3.8.6'  
   secrets:
      SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

  #2: Deploy
  deploy:
   needs: build
   uses: java-cicd-pipelines/java-reusable-pipelines/.github/workflows/package-deploy.yml@main
   secrets:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
     
